### ISSUE TITLE
No module named 'websockets'?

### ISSUE THREAD

**Issue by arlechinu** [sofakid/dandy#1]
Getting an error even though I have installed all the requirements, any idea what I might have done wrong? Thanks!

Traceback (most recent call last):
  File "D:\ComfyUI01\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI01\ComfyUI\custom_nodes\dandy\__init__.py", line 2, in <module>
    from .editors import *
  File "D:\ComfyUI01\ComfyUI\custom_nodes\dandy\editors.py", line 1, in <module>
    from .dandynodes import DandyWithHash
  File "D:\ComfyUI01\ComfyUI\custom_nodes\dandy\dandynodes.py", line 2, in <module>
    from .client import DandyServicesClient
  File "D:\ComfyUI01\ComfyUI\custom_nodes\dandy\client.py", line 2, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

Cannot import D:\ComfyUI01\ComfyUI\custom_nodes\dandy module for custom nodes: No module named 'websockets'

Requirement already satisfied: websockets in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (10.4)
Requirement already satisfied: matplotlib in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (3.8.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (1.4.5)
Requirement already satisfied: numpy>=1.21 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (1.25.0)
Requirement already satisfied: packaging>=20.0 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (23.1)
Requirement already satisfied: pillow>=8 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\bogdan\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 2)) (1.16.0)

**Comment by arlechinu** [comment]
retried and it works, nodes loaded ok

small typo in instructions: ..\..\..\python_embedded\python.exe -m pip install -r requirements.txt

comfy creates a folder called python_embeded not embedded, one 'd'

**Comment by sofakid** [comment]
thank you for noticing that typo, i fixed it. hope it's working well for you now!
