### ISSUE TITLE
DandyLand :: service_id is None

### ISSUE THREAD

**Issue by laurentVeliscek** [sofakid/dandy#3]
Hi !

I installed requirements
I installed websockets (no more missing websockets module message)
No error displayed when starting comfyUI, dandy is properly imported as a custom node.

But the nodes are not displayed properly (missing fields, missing inputs)

<img width="650" alt="Capture d’écran 2024-06-04 à 10 23 28" src="https://github.com/sofakid/dandy/assets/19191214/0d3db819-195b-4975-b277-7ca55994ed24">

And using some of your test workflows, I get this error :
 
```
DandyLand :: service_id is None
abort abort abort
Exception 
Traceback (most recent call last):
  File "/Users/lalala/pinokio/api/comfyui.git/app/custom_nodes/dandy-master/dandynodes.py", line 44, in execute
    return self.run(**kwargs)
  File "/Users/lalala/pinokio/api/comfyui.git/app/custom_nodes/dandy-master/dandyland.py", line 47, in run
    abort_abort_abort()
  File "/Users/lalala/pinokio/api/comfyui.git/app/custom_nodes/dandy-master/constants.py", line 97, in abort_abort_abort
    raise comfy.model_management.InterruptProcessingException
comfy.model_management.InterruptProcessingException
abort abort abort
Processing interrupted
Prompt executed in 0.06 seconds
```

Any idea ?

Thanks,

MacOs Sonoma, comfyUI installed with Pinokio,

**Comment by sofakid** [comment]
Ok so the node isn't connecting to the websocket, and when you run the prompt it doesn't have service id yet. Each node will have a websocket connection, i'm betting something is failing in the javascript creating the nodes, they look all wrong so they aren't set up completely.

Are there any errors in the Javascript console?

Which browser are you using? I haven't tried on macos or safari. (installing in a VM now, i'll try it out)

Are there any errors in the terminal when comfyui starts up?

I'm wondering about that path name, the dandy folder is called 'dandy-master' on your system. i'm wondering if comfy is sharing the web stuff under http://localhost.xxxx/dandy-master/stuff.js.. if it's doing that none of the javascript will be found, everything is looking for code at http:/localhost:xxxx/dandy/

as a first thing to try, i'd rename dandy-master to dandy.

but i'm wondering, is it Pinokio that does this? or did you just name it that?

**Comment by laurentVeliscek** [comment]
Hi, thanks for your answer !

I'm confused about not having the idea to open javascript console before...

:-/

My first attempt to install dandy was to unzip dandy_master.zip and install requirements. So I didn't rename the folder.

Strange thing, renaming the folder "dandy" seems to break my comfyUI. No more custom nodes, even comfyUI manager is not appearing anymore, so I guess there's a conflict somewhere...

Reinstalling dandy using git clone properly named the "dandy" folder, but didn't fixed the conflict. 
But I have so many custom nodes installed that the problem is definitely on my side.

Then I reinstalled a fresh comfyUI from scratch (no pinokio).
After installing websockets and matplotlib, (and comfyUi manager), everything seems to work fine now.

I'll let you know if I can find whitch custom node conflicts with dandy.

Combining javascript with stable diffusion is pretty exciting. Thanks for sharing !

**Comment by Gabrielmtn** [comment]
@laurentVeliscek I experienced the same with conflicts on a couple of nodes. I deactivated pythongosssss and mixlabs nodes, and it fixed the errors.

**Comment by sofakid** [comment]
Thank you for discovering these, and thanks for bearing with me, i will investigate these extensions.
